[platformio]
default_envs = cabin

[env]
framework = arduino
monitor_speed = 115200
build_flags = -I shared

[env:cabin]
platform = espressif32
board = esp32-s3-devkitc-1
build_src_filter = +<cabin/**>
build_flags =
  ${env.build_flags}
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_FONT_MONTSERRAT_28=1
  -DLV_FONT_MONTSERRAT_36=1
  -DLV_FONT_MONTSERRAT_48=1
lib_deps =
  lvgl/lvgl @ ^8.3.11
  adafruit/Adafruit ST7789 Library @ ^1.10.0
  adafruit/Adafruit LVGL Glue Library @ ^3.0.0

[env:engine-bay]
platform = espressif32
board = esp32-c3-devkitm-1
build_src_filter = +<engine_bay/**>
lib_deps =
  adafruit/Adafruit MAX31855 library @ ^1.4.0
  adafruit/Adafruit ADS1X15 @ ^2.4.0
